# Generated by Django 2.2.12 on 2020-05-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0005_auto_20200513_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lenguaje', models.CharField(max_length=45, null=True, verbose_name='Lenguaje de Programacion')),
                ('MotorDB', models.CharField(max_length=45, null=True, verbose_name='Base de Datos')),
                ('Arquitectura', models.CharField(max_length=45, null=True, verbose_name='Arquitectura de Software')),
            ],
            options={
                'verbose_name': 'Categoria Proyecto',
                'verbose_name_plural': 'Categorias de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDocu', models.CharField(max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos de Documeto',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombProy', models.CharField(max_length=45, null=True)),
                ('DescProy', models.TextField(verbose_name='Descripcion del proyecto')),
                ('ImgProye', models.ImageField(default='img.png', upload_to=None, verbose_name='Imagen del proyecto')),
                ('FechaIni', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('FechaFin', models.DateField(auto_now_add=True, null=True, verbose_name='Finalizado el')),
                ('UrlRepo', models.TextField(verbose_name='Ruta del Repositorio')),
                ('EstaProy', models.CharField(max_length=45, null=True, verbose_name='Estodo del proyeto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.CategProye')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombDocu', models.CharField(max_length=45, null=True, verbose_name='Nombre del Documento')),
                ('PathDocu', models.FileField(upload_to=None, verbose_name='Documento')),
                ('idDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.TipoDocu')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Proyectos')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
