# Generated by Django 2.2.12 on 2020-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocu',
            options={'verbose_name': 'Tipo Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='EstaProy',
            field=models.CharField(max_length=45, null=True, verbose_name='Estado del proyecto'),
        ),
        migrations.AlterField(
            model_name='tipodocu',
            name='NombDocu',
            field=models.CharField(max_length=45, null=True, verbose_name='Tipo Documento'),
        ),
    ]
